# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Everton da Rosa
email: everton3x@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Página pessoal do Everton3x, também conhecido como Everton da Rosa.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://everton3x.github.io" # the base hostname & protocol for your site
twitter_username: everton3x
github_username:  everton3x
timezone: America/Sao_Paulo
encoding: utf-8

# Build settings
markdown: kramdown
lsi: True #Produce an index for related posts. Requires the classifier-reborn plugin.

#defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Everton da Rosa"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Everton da Rosa"

theme: jekyll-theme-minimal