# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Everton da Rosa
email: everton3x@gmail.com
description: > # Everton da Rosa's GitHub Page.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: everton3x
github_username:  everton3x

# Build settings
markdown: kramdown

#personal settings
timezone: America/Sao_Paulo
encoding: utf-8
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            author: "Everton da Rosa"
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
            author: "Everton da Rosa"
